sudo: required

language: cpp

compiler:
  - gcc
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - arduino-core

env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
- export CXX="g++-7" CC="gcc-7"
- cp -r code/c/libraries/POCO_patches/* code/c/libraries/POCO/
- pushd code/c/libraries/POCO
- ./build_poco.sh
- popd

script: ./makeall.sh

notifications:
  email:
    recipients:
      - leo@leomeyer.de

