sudo: required

language: cpp

compiler:
  - gcc

install:
- pushd code/c/libraries/POCO
- ./build_poco.sh
- popd
- export CXX="g++-4.9" CC="gcc-4.9"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - arduino-core

script: ./makeall.sh

notifications:
  email:
    recipients:
      - leo@leomeyer.de

