language: cpp

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq arduino-core
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get install -qq g++-4.8

script: ./makeall.sh
