
# CPPFLAGS = 
CXXFLAGS += -fno-strict-aliasing
ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyUSB*
USER_LIB_PATH = libraries
ARDUINO_LIBS = EEPROM SPI Wire Wire/utility Keypad Keypad/utility Time rfid-master DS1307RTC
include /usr/share/arduino/Arduino.mk
