#!/bin/sh
# This script should work both for Windows and Linux.

cd ../lib/$1
echo Building nested library...
make

echo Cleaning up temporary files...
# This step causes the library to be re-built every time the pre-build step runs.
# This is necessary because we can't clean up the library folder explicitly because
# Eclipse does not pass the "clean" target to the pre-build step if Project->Clean... is used.
rm *.o

# Configure post build step (Ant build) to use selected library
# I have found no better way to pass the argument (from the Eclipse CDT configuration) to Ant, but this seems to work.
echo This file is autogenerated by build_lib.sh and used by Ant, do not edit >../../create_arduino_lib.properties
echo target=$1 >>../../create_arduino_lib.properties
